package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private EmployeeRepository employeeRepository;

    @PostMapping(path = "/add")
    public ResponseEntity addNewUser(@RequestParam String name) {
        User n = new User();
        Employee employee = new Employee();
        employee.setFirstName(name);
        n.setEmployee(employee);
        employeeRepository.save(employee);
        userRepository.save(n);
        return ResponseEntity.ok(n);
    }

    @GetMapping(path = "/all")
    public ResponseEntity getAllUsers() {
        return ResponseEntity.ok(employeeRepository.findAll());
    }
}
